package com.betha.backend.Enum;

public enum Status {
  DISPONIVEL_TRIAGEM,
  EM_TRIAGEM,
  AGUARDANDO_CLIENTE,
  CANCELADO,
  AGUARDANDO_MANUTENCAO,
  EM_MANUTENCAO,
  MANUTENCAO_REALIZADA,
  CONCLUIDO_CONSERTADO,
  CONCLUIDO_N_CONSERTADO
}
